root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/cli ./cmd/cli"
  bin = "./tmp/cli"
  
  include_ext = ["go", "yaml"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "docs"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = "500ms"

[log]
  time = true

[color]
  main = "yellow"      
  watcher = "cyan"
  build = "magenta"
  runner = "yellow"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true